CFLAGS += -Wall -Wextra -Werror -Wfatal-errors
CFLAGS += -I../include
CFLAGS += -g

VPATH += ..

.PHONY: all
all: list-targets

list-targets: list-targets.o -lmake

.PHONY: clean
clean:
	$(RM) list-targets list-targets.o

.PHONY: test
test:

.PHONY: install
install:

