set (CMAKE_SYSTEM_NAME Windows)

set (CMAKE_SYSTEM_ROOT "/usr/x86_64-w64-mingw32")

set (CMAKE_C_COMPILER "/usr/bin/x86_64-w64-mingw32-gcc")

set (CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set (CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set (CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set (CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
