#ifndef MAKE_OPERATION_H
#define MAKE_OPERATION_H

enum make_operation {
  MAKE_OPERATION_APPEND,
  MAKE_OPERATION_RECURSIVE,
  MAKE_OPERATION_STATIC,
  MAKE_OPERATION_CONDITIONAL
};

#endif /* MAKE_OPERATION_H */
